version: 2

references:
  test-steps: &test-steps
    steps:
      - checkout
      - restore_cache:
          name: Restore module caches
          keys:
            - go-modules-v1-{{ .Branch }}-{{ checksum "go.sum" }}
            - go-modules-v1-{{ .Branch }}-
            - go-modules-v1-
      - run:
          name: Install golangci-lint
          command: make -s install-golangci-lint
      - run:
          name: Run golangci-lint
          command: make -s golangci-lint
      - run:
          name: Test
          command: make -s test
      - save_cache:
          name: Save module caches
          key: go-modules-v1-{{ .Branch }}-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod

jobs:
  test-1.12:
    docker:
      - image: circleci/golang:1.12
    <<: *test-steps

  test-1.13:
    docker:
      - image: circleci/golang:1.13
    <<: *test-steps

workflows:
  version: 2
  test:
    jobs:
      - test-1.12
      - test-1.13
